Refactor VirtIO MMIO register map handling
sysprog21/semu pull request #23
Opened 2023-07-26 13:19 UTC by shengwen-tw

Two adjustments are conducted in this pull request:
1. Replace the hard-coded register address checking with enum.
2. Handle the configuration space read / write with device-specific structures.

2023-07-26 13:34 UTC, jserv commented on virtio.h
> +} VirtIO_MMIO_Reg_Map;
Avoid [Camel case](https://en.wikipedia.org/wiki/Camel_case).

2023-07-26 13:38 UTC, shengwen-tw commented
The CI failure is due to the wrong syntax of the enum, i.e.,
```
enum NAME {...}; //correct syntax
enum {...}  NAME; //wrong syntax
```
Where the compilation passed on my Ubuntu 20.04 machine but failed on the 22.04 version's machine.

2023-07-26 13:41 UTC, jserv commented
> The CI failure is due to the wrong syntax of the enum, i.e.,

You MUST use `clang-format-12`.

2023-07-26 13:42 UTC, jserv commented
> ```
> enum NAME {...}; //correct syntax
> enum {...}  NAME; //wrong syntax
> ```

Use `typedef`.

2023-07-26 14:16 UTC, shengwen-tw commented on virtio.h
> +    MagicValue = 0x000 >> 2,        /* R */
Neat!

2023-07-26 14:47 UTC, jserv commented on virtio.h
> +} VIRTIO_MMIO_REG_MAP;
Discard `VIRTIO_MMIO_REG_MAP` since its identifier does not matter.

2023-07-27 00:34 UTC, jserv requested changes
Move virtio-net and virtio-blk specific structure definitions from virtio.h to dedicated C source files.

Apply the trick [opaque pointer](https://en.wikipedia.org/wiki/Opaque_pointer) to hide the implementation details. That is, consider the following changes:
```diff
--- a/device.h
+++ b/device.h
@@ -144,14 +144,14 @@ typedef struct {
     /* queue config */
     uint32_t QueueSel;
     virtio_blk_queue_t queues[2];
-    /* device configuration */
-    struct virtio_blk_config config;
     /* status */
     uint32_t Status;
     uint32_t InterruptStatus;
     /* supplied by environment */
     uint32_t *ram;
     uint32_t *disk;
+    /* implementation-specific */
+    void *priv;
 } virtio_blk_state_t;
 
 void virtio_blk_read(vm_t *vm,
--- a/virtio-blk.c
+++ b/virtio-blk.c
@@ -21,6 +21,46 @@
 #define VBLK_QUEUE_NUM_MAX 1024
 #define VBLK_QUEUE (vblk->queues[vblk->QueueSel])
+
+#define PRIV(x) ((struct virtio_blk_config *) x->priv)
+
 static void virtio_blk_set_fail(virtio_blk_state_t *vblk)
 {
     vblk->Status |= VIRTIO_STATUS__DEVICE_NEEDS_RESET;
@@ -45,11 +85,11 @@ static void virtio_blk_update_status(virtio_blk_state_t *vblk, uint32_t status)
     /* Reset */
     uint32_t *ram = vblk->ram;
     uint32_t *disk = vblk->disk;
-    uint32_t capacity = vblk->config.capacity;
+    uint32_t capacity = PRIV(vblk)->capacity;
     memset(vblk, 0, sizeof(*vblk));
     vblk->ram = ram;
     vblk->disk = disk;
-    vblk->config.capacity = capacity;
+    PRIV(vblk)->capacity = capacity;
 }
 
 static void virtio_blk_write_handler(virtio_blk_state_t *vblk,
```

Of course, you have to allocate the necessary memory for the region pointed by `priv` member.

2023-07-27 01:47 UTC, jserv commented on virtio-blk.c
> +#define PRIV_INIT() malloc(sizeof(struct virtio_blk_config))
Don't invoke `malloc`. Use static allocation instead. Be aware of the fact that semu does not use `malloc` so far. semu is designed for minimal memory consumption.

You can prepare a static global object which is an instance of `struct virtio_blk_config` and then point `priv` to it.

2023-07-27 01:52 UTC, shengwen-tw commented on virtio-blk.c
> +#define PRIV_INIT() malloc(sizeof(struct virtio_blk_config))
That is fairly correct.

2023-07-27 01:56 UTC, jserv commented
> Should we also add destructor functions to clean up the allocated memory (i.e., `vnet->priv` and `vblk->priv`) explicitly even if the program will only be terminated by pressing Ctrl+A then X?

Yes, you can do it in next pull request(s).
Follow the way how [kvm-host](https://github.com/sysprog21/kvm-host) does.

2023-07-27 02:03 UTC, jserv commented on virtio-blk.c
> +        /* Undefined register before the configuration space */
You may introduce the `RANGE_CHECK` macro in `common.h`. See https://github.com/sysprog21/semu/blob/xv6/semu.c#L53
Then, you can rewrite as following:
```c
    if (!RANGE_CHECK(addr, _(Config), sizeof(struct virtio_blk_config)))
        return false;
```

2023-07-27 03:11 UTC, jserv commented on virtio-blk.c
> +        uint32_t *config = (uint32_t *) PRIV(vblk);
Simply rewrite as following:
```c
       *value = ((uint32_t *) PRIV(vblk))[addr - _(Config)];
```

This change avoids the mixture of `config` (lowercase) and `Config` (uppercase), which might confuse.

2023-07-27 03:11 UTC, jserv commented on virtio-net.c
> +        uint32_t *config = (uint32_t *) PRIV(vnet);
Ditto. Avoid the variable `config`.

2023-07-27 03:24 UTC, jserv requested changes
Rebase the latest `master` branch and resolve the conflicts.

2023-07-27 03:38 UTC, jserv commented on virtio-blk.c
> +    vblk->priv = (void *) &vblk_configs[vblk_dev_cnt++];
The cast to `void *` is not necessary as C standard allows implicit casting to `void *`.

2023-07-27 03:39 UTC, jserv commented on virtio-net.c
> +    vnet->priv = (void *) &vnet_configs[vnet_dev_cnt++];
Ditto. Remove unnecessary casting.

2023-07-27 03:46 UTC, jserv requested changes
Improve the git commit message. This commit addresses the following:
1. Re-organizes the source structures to improve code organization and maintainability.
2. Introduces the use of [opaque pointer](https://en.wikipedia.org/wiki/Opaque_pointer for information hiding, enhancing encapsulation and abstraction.
3. Enforces mnemonic enums instead of numbers, enhancing code readability and maintainability.

By incorporating these changes, the codebase becomes more structured, secure, and easier to understand and maintain."

2023-07-27 09:59 UTC, jserv requested changes
Rebase the latest `master` branch.

2023-07-27 13:44 UTC, merged

2023-07-27 13:44 UTC, jserv commented
Thank @shengwen-tw for contributing!