Implement SMP simulation for semu
sysprog21/semu pull request #46
Opened 2024-06-15 06:43 UTC by ranvd

In this commit, semu is able to simulate SMP architecture running on the Linux kernel.

Before simulating SMP on semu, you need to enable SMP support in the Linux kernel. Please cross-compile the Linux kernel with the configuration file located at configs/linux.config.

After recompiling the Linux kernel with SMP support enabled, simply execute `make check SMP=1` to simulate a quad-hart RISC-V core.

```
processor	: 0
hart		: 0
isa		: rv32ima_zicntr_zicsr_zifencei_zihpm
mmu		: sv32
mvendorid	: 0x12345678
marchid		: 0x80000001
mimpid		: 0x1
hart isa	: rv32ima_zicntr_zicsr_zifencei_zihpm

processor	: 1
hart		: 1
isa		: rv32ima_zicntr_zicsr_zifencei_zihpm
mmu		: sv32
mvendorid	: 0x12345678
marchid		: 0x80000001
mimpid		: 0x1
hart isa	: rv32ima_zicntr_zicsr_zifencei_zihpm

processor	: 2
hart		: 2
isa		: rv32ima_zicntr_zicsr_zifencei_zihpm
mmu		: sv32
mvendorid	: 0x12345678
marchid		: 0x80000001
mimpid		: 0x1
hart isa	: rv32ima_zicntr_zicsr_zifencei_zihpm

processor	: 3
hart		: 3
isa		: rv32ima_zicntr_zicsr_zifencei_zihpm
mmu		: sv32
mvendorid	: 0x12345678
marchid		: 0x80000001
mimpid		: 0x1
hart isa	: rv32ima_zicntr_zicsr_zifencei_zihpm
```

2024-06-15 16:32 UTC, jserv requested changes
Do not submit a single pull request that involves various independent commits. Instead, this pull request should be divided into at least three distinct parts as follows.
1. Modify the Linux kernel configurations to be SMP-aware, ensuring compatibility with both uniprocessor setups and implementations preceding SMP-related changes.
2. Manage RISC-V harts and hart state, along with CLINT support and peripheral supports. Separate these into as many distinct git commits as feasible. Of course, the new option "smp=" should be supported by semu command line.
3. Implement SMP-aware tests. The command `make SMP=n check` should be expanded where n represents the number of harts for system emulation. Here, `SMP=1` should be the default configuration, but it should be possible to specify `SMP=2` or more for testing purposes. Instead of using a file named `minimal-quad.dts`, generate 'minimal.dtsi' based on the specified SMP configurations using bash or Python scripts. This `minimal.dtsi` file will include definitions from `cpu@0` to `cpu@(n-1)` and can be included in the `minimal.dts` file.

2024-06-16 02:19 UTC, ranvd commented
Got it. I will separate this PR into more pull requests, and leave this pull request with the actual implementation of preliminary SMP implementation .

2024-06-24 18:10 UTC, jserv commented on main.c
> +        {"smp", 1, NULL, 's'},    {"help", 0, NULL, 'h'},
Use `-c` (core) for short representation of SMP option.

2024-06-24 18:17 UTC, jserv requested changes
Rebase the latest `master` branch.

2024-06-24 18:40 UTC, ranvd commented
In the commit log this time, I separate the commits of PLIC, CLINT implementation and LR/SC correction. Do I need to create new PR for each individual commit?

2024-06-25 01:42 UTC, jserv commented
> In the commit log this time, I separate the commits of PLIC, CLINT implementation and LR/SC correction. Does it needed to create new PR for each individual commit?

You can gather them in one pull request, but you should utilize `git rebase -i` to rework the commits, making them concise.

2024-06-25 01:49 UTC, jserv commented on Makefile
> +minimal.dtsi:
Rename to `riscv-harts.dtsi`.

2024-06-25 01:50 UTC, jserv commented on clint.c
> +    } else if (addr < 0xBFF8) {
Replace `else if` with `if`.

2024-06-25 01:50 UTC, jserv commented on clint.c
> +    } else if (addr < 0xBFFF) {
Ditto. Replace `else if` with `if`.

2024-06-25 01:50 UTC, jserv commented on clint.c
> +    } else if (addr < 0xBFF8) {
Ditto. Replace `else if` with `if`.

2024-06-25 01:52 UTC, jserv commented on scripts/dtsi-gen.py
> +import sys
Rename this file to `scripts/gen-harts-dts.py`.

2024-06-25 04:51 UTC, ranvd commented
> You can gather them in one pull request, but you should utilize `git rebase -i` to rework the commits, making them concise.

Sorry, I can't understand what exactly I should do. The current commit is already rebased to the latest master branch. Does "Rework the commits" mean I need to rewrite the commit message because my commit message is not clear enough to convey the idea of changes?

2024-06-25 05:56 UTC, jserv commented
> Does "Rework the commits" mean I need to rewrite the commit message because my commit message is not clear enough to convey the idea of changes?

The requested changes are involved in several functional and minimal commits which refer to their individual change lists. e.g.,
* Adapt Linux kernel configurations for SMP-awareness
* Introduce CLINT for multi-harts
* Fix atomic instructions for SMP
* Introduce SMP-aware option and runtime support

While the following changes should be amended into the above. e.g.,
* Change device tree related file name
* Enhance coding sytle in clint.c

Each commit should be fully traceable and well-understood.

2024-06-25 06:28 UTC, jserv commented on main.c
> +    /* TODO */
Make the comment informative.

2024-06-25 06:28 UTC, jserv commented on main.c
> +    int hart_number = 1;
Rename to `hart_count`.

2024-06-25 06:29 UTC, jserv commented on minimal.dts
> +#include "riscv-harts.dtsi"
Add some comments such as "RISC-V hart descriptions."

2024-06-25 06:30 UTC, jserv commented on riscv.c
> +        uint8_t idx = __builtin_ffs(applicable) - 1;
You should provide the wrapper function in `common.h` to improve the portability.

2024-06-26 01:34 UTC, jserv commented on common.h
> +static inline int ffs(int x)
The `ffs()` function appeared in 4.3BSD.  Its prototype existed previously in <string.h> before it was moved to <strings.h> for IEEE Std 1003.1-2001 ("POSIX.1") compliance.

You can include `<strings.h>` when needed.

2024-06-26 01:37 UTC, jserv commented on riscv.h
> +    uint32_t hart_number;
Rename to `n_harts` for consistency.

2024-06-26 01:40 UTC, jserv commented on virtio-blk.c
> +void virtio_blk_read(hart_t *vm,
For the sake of consistency, the first parameter should be exactly `vm` which points to the instance of virtual machine regardless of its hart configuration.

2024-06-26 03:46 UTC, ranvd commented on riscv.h
> +    uint32_t hart_number;
Is it better to rename it to `hart_count`? Since the variable name storing the `--smp` argument value is `hart_count`, which will be used to initialize `vm.hart_number`.

2024-06-26 03:51 UTC, jserv commented on riscv.h
> +    uint32_t hart_number;
Count is to enumerate one by one. Number is either total or status of anything in a series. So, we would "number" or the short form "n_" in structures. Meanwhile, we use count during initialization to emphasize the enumeration.

2024-06-26 03:56 UTC, jserv commented on clint.c
> +static bool clint_reg_read(clint_state_t *clint, uint32_t addr, uint32_t *value)
Specify `const` qualifier when possible. i.e., `const clint_state_t *clint`.

2024-06-30 11:57 UTC, ranvd commented
I found that some implementations are not consistent with the specifications. I will update this branch afterward.

2024-07-03 18:59 UTC, jserv requested changes
Use `git rebase -i` to consolidate the commits and classify them properly.

2024-07-08 11:52 UTC, jserv commented
Can you integrate SMP aware tests in GitHub Actions?

2024-07-08 13:04 UTC, ranvd commented
Okay, I will integrate it in other pull request afterward.

2024-07-10 06:04 UTC, merged

2024-07-10 06:04 UTC, jserv commented
Thank @ranvd for contributing!