Replace mtime counter with realtime timer
sysprog21/semu pull request #49
Opened 2024-07-14 19:35 UTC by chiangkd

Replace `mtime` counter by retrieving time of the specified clock ID. Also, Real time counter (RTC) mechanism is implemented to prevent `mtime` overflow.

Before:
```
[    0.000000] Linux version 6.1.94 (aaron@aaron-Lenovo-Y520-15IKBN) (riscv32-buildroot-linux-gnu-gcc.br_real (Buildroot 2024.02.3) 12.3.0, GNU ld (GNU Binutils) 2.41) #8 SMP Thu Jul 11 00:37:05 CST 2024
[    0.000000] Machine model: semu
[    0.000000] earlycon: ns16550 at MMIO 0xf4000000 (options '')
[    0.000000] printk: bootconsole [ns16550] enabled
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
...
[    2.687661] Freeing initrd memory: 8188K
[    2.691697] Freeing unused kernel image (initmem) memory: 180K
[    2.691978] Kernel memory protection not selected by kernel config.
[    2.692277] Run /init as init process

```
Now:
```
[    0.000000] Linux version 6.1.94 (aaron@aaron-Lenovo-Y520-15IKBN) (riscv32-buildroot-linux-gnu-gcc.br_real (Buildroot 2024.02.3) 12.3.0, GNU ld (GNU Binutils) 2.41) #10 SMP Mon Jul 15 02:47:57 CST 2024
[    0.000000] Machine model: semu
[    0.000000] earlycon: ns16550 at MMIO 0xf4000000 (options '')
[    0.000000] printk: bootconsole [ns16550] enabled
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
...
[   73.908933] Freeing initrd memory: 8188K
[   74.033405] Freeing unused kernel image (initmem) memory: 180K
[   74.044397] Kernel memory protection not selected by kernel config.
[   74.064088] Run /init as init process
```
Revised boot log to display actual timer during boot flow.

Reference to RVVM:https://github.com/LekKit/RVVM/blob/staging/src/rvtimer.c

However, another issue accopanies this PR
```
[   32.038173] rcu: INFO: rcu_sched self-detected stall on CPU
[   32.043867] rcu: 	3-....: (5248 ticks this GP) idle=846c/1/0x40000002 softirq=371/371 fqs=2114
[   32.055848] 	(t=5251 jiffies g=-883 q=10 ncpus=4)
[   32.064761] CPU: 3 PID: 39 Comm: kworker/u8:1 Not tainted 6.1.94 #10
```
RCU issues a CPU stall wrning when it waits more than a grace period, which is normally 21 seconds.

Detail here: https://docs.kernel.org/RCU/stallwarn.html

2024-07-15 01:04 UTC, jserv commented on timer.h
> +/* TIMER */
Let's put all the definitions about devices such as timer into the header `device.h`.

2024-07-15 11:53 UTC, ranvd commented on clint.c
> +    if (time_delta & 0x8000000000000000 || time_delta == 0)
Is it better to make `time_delta` an `int64_t` instead of unsigned integer? By doing this, the comparison in the `if` statement can be reduced and more intuitive.

2024-07-15 12:06 UTC, ranvd commented
I believe using a real-time counter is a better approach for simulating the timer device. However, I didn't notice any differences between the "Before" and "Now" sections in your text.

Also, Could you please explain how to reproduce the RCU issues you mentioned? Thank you.

2024-07-15 14:06 UTC, ranvd commented
> I believe using a real-time counter is a better approach for simulating the timer device. However, I didn't notice any differences between the "Before" and "Now" sections in your text.

Sorry I need to take back what I said earlier. The real-time counter may not always be a better implementation. After measuring the boot-up time with SMP=4, the original version takes around 23 seconds, while this commit takes 39 seconds. I think this is because the real-time counter generates more interrupts then the original version.

Does the real-time counter (RTC) provide any features that can't be neglected?

2024-07-15 15:46 UTC, chiangkd commented on clint.c
> +    if (time_delta & 0x8000000000000000 || time_delta == 0)
You are correct, casting `time_delta` can be more intutive. Below is the refined implementation
```c
uint64_t time_delta =
    clint->mtimecmp[hart->mhartid] - semu_timer_gettime(&hart->time);
if ((int32_t)time_delta <= 0)
...
```

2024-07-15 16:38 UTC, chiangkd commented
> Does the real-time counter (RTC) provide any features that can't be neglected?

Initially, my intention was to enable the actual clock for the RDTIME (0xC01/0xC81) pseudo-instruction, which originally retrieves the monotonic-incremented `mtime`. I did not anticipate that this PR would trigger RCU warnings prior to implementation. Post-implementation, real timestamps are visible in the booting log due to CONFIG_PRINTK_TIME being enabled by default.

>SEMU becomes slower as the number of simulated harts grows.

I acknowledge the observation that SEMU slows down as the number of simulated harts increases. While reducing the frequency in `semu_timer_init` might mitigate this, it would compromise the provision of an actual clock through the TIMER CSR. In my undetstanding, simulating a multi-core system with a single thread inherently reduces efficiency(include much more timer interrupt and much more `clock_gettime` system call in this PR), leading to RCU warnings.
>Since RVVM is a multi-threaded RISC-V simulator, it's okay to directly simulate the timer as you implemented.

I believe implementing multi-threaded simulation for SEMU could provide a better solution to the RCU warning issue, is that make sense?

2024-07-15 17:22 UTC, chiangkd commented on timer.h
> +/* TIMER */
I chose to separate timer.h because timer devices need to be accessible in both `hart_t` and `clint_state_t`. Should I move its contents to `common.h`?

2024-07-17 10:14 UTC, jserv commented on timer.h
> +/* TIMER */
> I chose to separate `timer.h` because timer devices need to be accessible in both `hart_t` and `clint_state_t`. Should I move its contents to `common.h`?

Move to `utils.[ch]` to avoid potential confusions. When we say "timer," we refer to the peripherals at first glance.

2024-07-19 00:44 UTC, jserv commented on main.c
> +    semu_timer_init(&emu.clint.mtime, 65000000);
Make it configurable. That is, don't hardcode `65000000`.

2024-07-20 15:47 UTC, jserv requested changes
Squash the git commits and rebase the latest `master` branch.

2024-07-21 16:50 UTC, jserv commented
Properly rebase the latest `master` branch via the following commands:
```shell
$ git remote add upstream https://github.com/sysprog21/semu
$ git fetch upstream 
$ git rebase upstream/master
$ git push --force origin master
```

Next time, create a dedicated branch rather than `master` branch when you are going to submit pull requests.

2024-07-21 16:56 UTC, chiangkd commented
> Next time, create a dedicated branch rather than `master` branch when you are going to submit pull requests.

Thank you for the instructions. I understand and will follow these steps and will also make sure to create a dedicated branch for future PR.

2024-07-21 17:03 UTC, jserv requested changes
Improve the git commit message. You should explain the rationale.
See https://cbea.ms/git-commit/

2024-07-21 17:25 UTC, jserv commented on utils.h
> +uint64_t semu_timer_clocksource(uint64_t freq);
It is not necessary to expose `semu_timer_clocksource`. Make it a static function.

2024-07-21 18:27 UTC, jserv commented on utils.h
> +#define TIMER_FREQUENCY 65000000
Don't specify here. Instead, define in `Makefile`. e.g.,
```
DT_CFLAGS := -D TIMER_FREQ=65000000
CFLAGS += $(DT_CFLAGS)
```

The device tree should be changed accordingly. That is,
```diff
--- a/Makefile
+++ b/Makefile
@@ -70,6 +73,7 @@ S := $E $E
 minimal.dtb: minimal.dts
        $(VECHO) " DTC\t$@\n"
        $(Q)$(CC) -nostdinc -E -P -x assembler-with-cpp -undef \
+           $(DT_CFLAGS) \
            $(subst ^,$S,$(filter -D^SEMU_FEATURE_%, $(subst -D$(S)SEMU_FEATURE,-D^SEMU_FEATURE,$(CFLAGS)))) $< \
            | $(DTC) - > $@
 
--- a/minimal.dts
+++ b/minimal.dts
@@ -19,7 +19,7 @@
     cpus {
         #address-cells = <1>;
         #size-cells = <0>;
-        timebase-frequency = <65000000>;
+        timebase-frequency = <CLOCK_FREQ>;
         cpu0: cpu@0 {
             device_type = "cpu";
             compatible = "riscv";
```

2024-07-22 13:53 UTC, ranvd commented on clint.c
> +    if ((int32_t) time_delta <= 0)
I think using `int32_t` might trigger potential errors since this is a real-time counter. We can't predict when the `clint_update_interrupts` function will be executed. The time_delta could be a very small negative value, which would normally trigger the timer interrupt. However, if we cast it into a 32-bit integer, the value could incorrectly become positive. For example, if `time_delta` is 0xFFFFFFFF00000001, which is -4294967295, casting it to `int32_t` will result in the value becoming 1.

Therefore, I suggest using `int64_t` instead.

2024-07-22 13:55 UTC, ranvd commented on clint.c
> +    if ((int32_t) time_delta <= 0)
I think using `int32_t` might trigger potential errors since this is a real-time counter. We can't predict when the `clint_update_interrupts` function will be executed. The time_delta could be a very small negative value, which would normally trigger the timer interrupt. However, if we cast it into a 32-bit integer, the value could incorrectly become positive. For example, if `time_delta` is 0xFFFFFFFF00000001, which is -4294967295, casting it to `int32_t` will result in the value becoming 1.

Therefore, I suggest using `int64_t` instead.

2024-07-22 17:46 UTC, chiangkd commented on clint.c
> +    if ((int32_t) time_delta <= 0)
Yes, you're absolutely right. When the larger number exceeds the small one by more than 0x100000000, it will incorrectly cast a negative number to a positive one. Thanks for pointing that out!

2024-07-24 18:33 UTC, jserv commented on utils.h
> +#include <stdbool.h>
Don't include `<stdbool.h>` since it is not used.

2024-07-24 18:33 UTC, jserv commented on utils.h
> +
Keep only one blank line.

2024-07-24 18:37 UTC, jserv requested changes
Read https://cbea.ms/git-commit/ carefully and refine your git commit messages.
> Wrap the body at 72 characters

Avoid using [backticks](https://en.wikipedia.org/wiki/Backtick) in git commit messages and comments to ensure compatibility with terminal emulators that may not render the backtick character properly.

Instead, use the pair `'` or `"` (quotation marks).

2024-07-25 10:21 UTC, jserv commented on utils.h
> +uint64_t semu_timer_gettime(semu_timer_t *timer);
Let's unify the naming scheme. That is, consider the following functions:
* `semu_timer_init`
* `semu_timer_get`
* `semu_timer_rebase`

Thus, they all have the consistent prefix and the manner to perform actions.

2024-07-25 10:26 UTC, chiangkd commented on utils.h
> +
Is it sensible to modify `MaxEmptyLinesToKeep` in `.clang-format` from 3 to 1?

2024-07-25 10:31 UTC, jserv commented on utils.h
> +
> Is it sensible to modify `MaxEmptyLinesToKeep` in `.clang-format` from 3 to 1?

No, stick to the current `MaxEmptyLinesToKeep` setting. Sometimes, we do need blank lines. This is particularly true for domain-specific languages with C preprocessor enablement.

2024-07-25 10:45 UTC, chiangkd commented on utils.h
> +
Got it, thanks.

2024-07-25 11:17 UTC, jserv commented
> SEMU experiences a slowdown as the number of simulated harts increases. This is due to the increased number of timer interrupts and `clock_gettime` system calls in this commit.

Have you tried `CLOCK_REALTIME` as the clock source?

2024-07-25 12:52 UTC, chiangkd commented
> Have you tried `CLOCK_REALTIME` as the clock source?

Yes, `CLOCK_REALTIME` perform a similar result for booting system. `CLOCK_REALTIME` is affected by NTP. In the absence of time adjustments, `CLOCK_REALTIME` and `CLOCK_MONOTIC` might show similar time differences.

Execute with `CLOCK_REALTIME`
```
[   32.718809] rcu: INFO: rcu_sched self-detected stall on CPU
...
[   76.194389] Run /init as init process
```

Execute with `CLOCK_MONOTIC`
```
[   32.545280] rcu: INFO: rcu_sched self-detected stall on CPU
...
[   74.768311] Run /init as init process
```

2024-07-25 13:06 UTC, jserv commented
> `CLOCK_REALTIME` perform a similar result for booting system. `CLOCK_REALTIME` is affected by NTP. In the absence of time adjustments, `CLOCK_REALTIME` and `CLOCK_MONOTIC` might show similar time differences.

How about `CLOCK_MONOTONIC_RAW` or `CLOCK_MONOTONIC_COARSE`? 
They are implemented as faster but less precise alternatives of `CLOCK_MONOTONIC`.

2024-07-25 17:15 UTC, chiangkd commented
> How about `CLOCK_MONOTONIC_RAW` or `CLOCK_MONOTONIC_COARSE`?
> They are implemented as faster but less precise alternatives of `CLOCK_MONOTONIC`.

`CLOCK_MONOTONIC_COARSE` and `CLOCK_REALTIME_COARSE` can be faster because they use less precise and vDSO mechanism. However, they can still trigger RCU warnings.

Execute with `CLOCK_MONOTONIC_COARSE`
```
[   29.840317] rcu: INFO: rcu_sched self-detected stall on CPU
...
[   62.512664] Run /init as init process
...

```
Execute with `CLOCK_REALTIME_COARSE`
```
[   29.979120] rcu: INFO: rcu_sched self-detected stall on CPU
...
[   56.826371] Run /init as init process
```

Use `perf` to monitor performance for different clock sources during 100,000,000 calls to clock_gettime().
|| MONOTONIC | REALTIME | MONOTONIC_COARSE | REALTIME_COARSE |
|-------------| ------------- | ------------- |------------- | ------------- |
|`user`| 1.723s  | 1.796s |0.556s |0.568s|
|`sys`|  0s |  0.008 |0s | 0s|

2024-07-26 01:53 UTC, jserv commented
> `CLOCK_MONOTONIC_COARSE` and `CLOCK_REALTIME_COARSE` can be faster because they use less precise and vDSO mechanism. However, they can still trigger RCU warnings.

Based on the experiments, empirical evidence suggests utilizing `CLOCK_MONOTONIC_COARSE`, which is available on modern Linux systems. Please submit a GitHub issue regarding RCU warnings once this pull request is merged.

2024-07-28 16:54 UTC, jserv commented
I defer to @ranvd for confirmation.

2024-08-01 06:55 UTC, merged

2024-08-01 06:56 UTC, jserv commented
Thank @chiangkd for contributing!