Implement VirtIO sound device
sysprog21/semu pull request #53
Opened 2024-08-31 08:17 UTC by Cuda-Chen

Implement VirtIO sound device.

2024-08-31 09:06 UTC, shengwen-tw commented
Please provide testing procedures once the change is ready.

2024-08-31 11:46 UTC, jserv commented on CNFA_sf.h
> +// This file was automatically generated by Makefile at
Don't copy the C source from [cnfa](https://github.com/cnlohr/cnfa). Instead, use git submodule.

2024-08-31 11:47 UTC, jserv commented on virtio-snd.c
> +#include "common.h"
You don't have to include `common.h`.

2024-09-01 06:06 UTC, Cuda-Chen commented on virtio-snd.c
> +#include "common.h"
Fixed.

2024-09-01 06:32 UTC, jserv commented on configs/linux.config
> +CONFIG_CPU_ISOLATION=y
Avoid changing this.

2024-09-01 06:32 UTC, jserv commented on configs/linux.config
> +#
Minimize the necessary changes.

2024-09-01 06:34 UTC, jserv commented on os_generic.h
> +#ifndef _OS_GENERIC_H
Can you avoid putting this header into repository?

2024-09-01 13:21 UTC, Cuda-Chen commented on CNFA_sf.h
> +// This file was automatically generated by Makefile at
Done.

2024-09-01 13:22 UTC, Cuda-Chen commented on configs/linux.config
> +CONFIG_CPU_ISOLATION=y
Fixed. Use `make savedefconfig` to get the minimal config of Linux Kernel building.

2024-09-01 13:22 UTC, Cuda-Chen commented on configs/linux.config
> +#
Fixed.

2024-09-01 13:26 UTC, Cuda-Chen commented on os_generic.h
> +#ifndef _OS_GENERIC_H
Fixed. As it is merely used in `cnfa`, download in the `cnfa` module instead.

2024-09-01 14:37 UTC, jserv commented on Makefile
> +cnfa_dep:
Specify git submodule for cnfa.

2024-09-01 14:38 UTC, jserv commented on configs/linux.config
> -CONFIG_CC_VERSION_TEXT="riscv32-buildroot-linux-gnu-gcc.br_real (Buildroot 2023.05.1) 12.3.0"
Honor the existing configurations. Minimize the necessary changes.

2024-09-01 14:38 UTC, jserv commented on virtio-snd.c
> +#include <assert.h>
If `assert` is unused, drop the header inclusion.

2024-09-01 14:39 UTC, jserv commented on virtio-snd.c
> +#define VSND_FEATURES_0 0
Use `enum` for `VSND_FEATURES_0` and `VSND_FEATURES_1`.

2024-09-01 14:39 UTC, jserv requested changes
Run `clang-format` before submitting.

2024-09-02 08:29 UTC, jserv commented on .gitmodules
> +	url = https://github.com/cntools/cnfa.git
Use shorter form. That is, `https://github.com/cntools/cnfa` .

2024-09-02 08:30 UTC, jserv commented on Makefile
> +CFLAGS += -include common.h -I./cnfa
`-Icnfa` is only valid when VirtIO-sound is enabled.

2024-09-02 08:32 UTC, jserv commented on Makefile
> +    CFLAGS += -I/usr/local/include
Don't specify `-I/usr/local/include`.

2024-09-02 08:35 UTC, jserv requested changes
Consult https://github.com/cntools/cnfa/blob/master/.github/workflows/build-cnfa.yml and mention the build dependency in top-level `README.md`.

2024-09-02 08:37 UTC, jserv commented on Makefile
> +cnfa_dep:
Add corresponding rules. e.g., https://github.com/cntools/cnfa/blob/master/.github/workflows/build-cnfa.yml

2024-09-02 08:39 UTC, jserv commented on configs/linux.config
> +CONFIG_SND_VIRTIO=y
Insert these lines without touching other regions.

2024-09-02 08:43 UTC, jserv commented on feature.h
> +#define SEMU_FEATUREVIRTIOSND 1
Should be `SEMU_FEATURE_VIRTIOSND`.

You can send another pull request to fix `SEMU_FEATURE_VIRTIOBLK` and `SEMU_FEATURE_VIRTIONET`. Check `Makefile` for `SEMU_FEATURE_`.

2024-09-03 08:41 UTC, Cuda-Chen commented on feature.h
> +#define SEMU_FEATUREVIRTIOSND 1
Make a PR in https://github.com/sysprog21/semu/pull/56.

2024-09-03 08:46 UTC, jserv commented on feature.h
> +#define SEMU_FEATUREVIRTIOSND 1
Rebase the latest `master` branch

2024-09-03 09:03 UTC, Cuda-Chen commented on Makefile
> +CFLAGS += -include common.h -I./cnfa
Fixed.

2024-09-03 09:03 UTC, Cuda-Chen commented on Makefile
> +    CFLAGS += -I/usr/local/include
Fixed.

2024-09-03 09:03 UTC, Cuda-Chen commented on feature.h
> +#define SEMU_FEATUREVIRTIOSND 1
Done.

2024-09-03 09:03 UTC, Cuda-Chen commented on .gitmodules
> +	url = https://github.com/cntools/cnfa.git
Done.

2024-09-03 09:13 UTC, jserv commented on README.md
> +$ git submodule init
Don't do that. Add rules in top-level `Makefile`.

2024-09-03 09:13 UTC, jserv commented on README.md
> +Build the dependency (CNFA):
Don't do that. Refine `Makefile` to aggregate the rules.

2024-09-03 09:14 UTC, jserv commented on configs/linux.config
> +# Linux/riscv 6.1.107 Kernel Configuration
Don't change version specific items.

2024-09-03 09:15 UTC, jserv commented on feature.h
> +#define SEMU_FEATUREVIRTIOSND 1
> Done.

Not yet.

2024-09-03 10:49 UTC, Cuda-Chen commented on README.md
> +Build the dependency (CNFA):
Thanks for the advice. I will pay attention to `rv32emu` build system.

2024-09-03 12:03 UTC, Cuda-Chen commented on configs/linux.config
> +CONFIG_SND_VIRTIO=y
Done.

2024-09-03 13:09 UTC, Cuda-Chen commented on configs/linux.config
> +# Linux/riscv 6.1.107 Kernel Configuration
Fixed.

2024-09-03 13:40 UTC, jserv commented on device.h
> +
Remove this blank line.

2024-09-03 13:52 UTC, jserv commented on virtio-snd.c
> +#define VSND_QUEUE (vsnd->queues[vsnd->QueueSel])
Use shorter form. e.g., `vsndq`.

2024-09-05 01:54 UTC, Cuda-Chen commented on Makefile
> +	$(MAKE) -C $(dir $<) CC=$(CC) CNFA_sf.h
The target `cnfa/Makefile` make the `make` command stops here after the `cnfa` sub-module initialization.
I will come up with another solution to conquer this issue.

2024-09-05 02:22 UTC, jserv commented on Makefile
> +	$(MAKE) -C $(dir $<) CC=$(CC) CNFA_sf.h
Consider the following:
```diff
--- a/Makefile
+++ b/Makefile
@@ -51,17 +51,22 @@ endif
 $(call set-feature, VIRTIOSND)
 ifeq ($(call has, VIRTIOSND), 1)
     OBJS_EXTRA += virtio-snd.o
-    LDFLAGS += -lasound
+    LDFLAGS += -lasound -lpthread
     CFLAGS += -Icnfa
 
 cnfa/Makefile:
-       git submodule update --init cnfa/
-CNFA_LIB := cnfa/CNFA_sf.h
-$(CNFA_LIB): cnfa/Makefile
+       git submodule update --init cnfa
+cnfa/os_generic: cnfa/Makefile
        $(MAKE) -C $(dir $<) CC=$(CC) os_generic.h
+CNFA_LIB := cnfa/CNFA_sf.h
+$(CNFA_LIB): cnfa/Makefile cnfa/os_generic
        $(MAKE) -C $(dir $<) CC=$(CC) CNFA_sf.h
 endif
 
+# .DEFAULT_GOAL should be set to all since the very first target is not all
+# after git submodule.
+.DEFAULT_GOAL := all
+
 BIN = semu
 all: $(BIN) minimal.dtb

```

2024-09-05 02:27 UTC, jserv commented on virtio-snd.c
> +
Remove this blank line.

2024-09-05 04:49 UTC, Cuda-Chen commented on virtio-snd.c
> +#define VSND_QUEUE (vsnd->queues[vsnd->QueueSel])
> Use shorter form. e.g., `vsndq`.

I think it will be something like this?

```
#define vsndq (vsnd->queues[vsnd->QueueSel]) // change from VSND_QUEUE to vsndq for simplicity
```

2024-09-05 04:50 UTC, Cuda-Chen commented on virtio-snd.c
> +
Done.

2024-09-05 04:51 UTC, Cuda-Chen commented on device.h
> +
Done.

2024-09-05 04:51 UTC, jserv commented on virtio-snd.c
> +#define VSND_QUEUE (vsnd->queues[vsnd->QueueSel])
Yes, it leads to shorter and elegant code.

2024-09-05 04:52 UTC, Cuda-Chen commented on Makefile
> +	$(MAKE) -C $(dir $<) CC=$(CC) CNFA_sf.h
Thank for the suggestions! Done.

2024-09-05 04:52 UTC, Cuda-Chen commented on README.md
> +Build the dependency (CNFA):
Done by aggregating the rules in `Makefile`.

2024-09-05 04:53 UTC, Cuda-Chen commented on README.md
> +$ git submodule init
Done.

2024-09-05 04:57 UTC, jserv commented on .gitmodules
> +	path = cnfa
Make the indention more consistent.

2024-09-05 05:06 UTC, jserv commented on Makefile
> +	$(MAKE) -C $(dir $<) CC=$(CC) os_generic.h
The assignment `CC=$(CC)` is redundant because environment variables are automatically inherited by subprocesses.

2024-09-05 05:07 UTC, jserv commented on Makefile
> +ifneq ($(UNAME_S),Linux)
You shall check the existence of ALSA headers and library in advance.

2024-09-05 05:26 UTC, jserv commented on README.md
> +    - virtio-snd uses ALSA.
Improve this description.

2024-09-06 07:31 UTC, jserv commented on virtio-snd.c
> +
Remove this blank line.

2024-09-06 07:32 UTC, jserv commented on virtio-snd.c
> +} virtio_snd_chmap_info;
Specify the `_t` suffix. Check `CONTRIBUTING.md` for details.

2024-09-06 07:32 UTC, jserv commented on virtio-snd.c
> +} virtio_snd_pcm_info;
Check `CONTRIBUTING.md` for type definitions.

2024-09-06 07:33 UTC, jserv commented on virtio-snd.c
> +    uint32_t size;  // size of a singly reply
Refine the comment.

2024-09-07 16:11 UTC, jserv commented on virtio-snd.c
> +    audio_host = CNFAInit(NULL, "semu-virtio-snd", cnfa_audio_cb, 44100, 0, 1,
Check the return value.

2024-09-07 16:12 UTC, jserv commented on configs/linux.config
> +CONFIG_SND_DEBUG=y
Remove the debug configurations.

2024-09-07 16:12 UTC, jserv commented on configs/linux.config
> +CONFIG_SND_DUMMY=y
Is the dummy sound device required?

2024-09-08 06:24 UTC, jserv requested changes
Install ALSA packages and trigger CI builds.

2024-09-08 07:36 UTC, Cuda-Chen commented on Makefile
> +ifneq ($(UNAME_S),Linux)
Thanks for the suggestion.

Currently, I use `pkg-config` to check whether `libasound2-dev` is installed or not. The `pkg-config` says no `libasound2-dev` is installed even though the `.pc` files is existed.
I will start to investigate the root cause of this issue if I still want to use `pkg-config` to get the compilation flags of `libasound2-dev`.

2024-09-08 07:48 UTC, jserv commented on Makefile
> +ifneq ($(UNAME_S),Linux)
You can generate a C source file and attempt to compile and link it to check for the presence of ALSA headers and libraries.

2024-09-08 07:49 UTC, jserv commented on configs/buildroot.config
> +BR2_PACKAGE_ALSA_UTILS_SPEAKER_TEST=y
Is `BR2_PACKAGE_ALSA_UTILS_SPEAKER_TEST` required and functioned?

2024-09-08 07:51 UTC, jserv commented on virtio-snd.c
> +        printf("cnfa_audio_cb(%p, %p, %p, %d, %d)\n", dev, out, in, framesp,
Don't mention cnfa. Instead, emphasize virtio-snd.

2024-09-08 07:53 UTC, jserv commented on virtio-snd.c
> +static struct CNFADriver *audio_host = NULL;
Can this variable declared as non-global one?

2024-09-08 07:54 UTC, Cuda-Chen commented on configs/buildroot.config
> +BR2_PACKAGE_ALSA_UTILS_SPEAKER_TEST=y
The `speaker-test` (in buildroot it is enabled by `BR2_PACKAGE_ALSA_UTILS_SPEAKER_TEST`) is required for testing the speaker (the virtio-snd).

For functionality, though it can't play sound as the sound playing feature in virtio-snd is not implemented yet, it can function as shows in the following:

```
Welcome to Buildroot
buildroot login: root
# speaker-test

speaker-test 1.2.11

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
ALSA lib pcm_direct.c:2188:(_snd_pcm_direct_new) unable to create IPC semaphore
Playback open error: -38,Function not implemented
```

2024-09-08 07:54 UTC, jserv commented on virtio-snd.c
> +static int vsnd_dev_cnt = 0;
Can you check if `vsnd_dev_cnt` is assigned properly?

2024-09-08 07:55 UTC, jserv commented on virtio-snd.c
> +        uint16_t buffer_idx = ram[queue->QueueAvail + 1 + queue_idx / 2] >>
More explanations for buffer index are needed.

2024-09-08 07:56 UTC, jserv commented on configs/buildroot.config
> +BR2_PACKAGE_ALSA_UTILS_SPEAKER_TEST=y
You should clarify the limitations and known issues.

2024-09-08 07:59 UTC, jserv commented on main.c
> +            virtio_snd_write(hart, &data->vsnd, addr & 0xFFFFF, width, value);
Is it better to use `UINT16_MAX` rather than `0xFFFFF`?

2024-09-08 08:00 UTC, jserv commented on virtio-snd.c
> +    return addr >> 2;
More comments for this function.

2024-09-08 08:01 UTC, jserv commented on virtio-snd.c
> +        fprintf(stderr, "CNFADriver initialization failed.\n");
Don't mention `CNFADriver`. Emphasize on virtio-snd instead.

2024-09-08 09:45 UTC, Cuda-Chen commented on configs/buildroot.config
> +BR2_PACKAGE_ALSA_UTILS_SPEAKER_TEST=y
Mention the question for implementation in https://github.com/sysprog21/semu/issues/50#issuecomment-2336619392.

2024-09-08 11:56 UTC, Cuda-Chen commented on virtio-snd.c
> +#define VSND_QUEUE (vsnd->queues[vsnd->QueueSel])
Done.

2024-09-09 13:14 UTC, Cuda-Chen commented on virtio-snd.c
> +        printf("cnfa_audio_cb(%p, %p, %p, %d, %d)\n", dev, out, in, framesp,
Done.

2024-09-11 04:57 UTC, Cuda-Chen commented on main.c
> +            virtio_snd_write(hart, &data->vsnd, addr & 0xFFFFF, width, value);
For my knowing, `UINT16_MAX` will be 65535 or `0xFFFF`, whereas we are getting the address in [0, `0xFFFFF`] range.

2024-09-12 14:35 UTC, jserv commented
Is System V IPC required?

2024-09-12 15:03 UTC, Cuda-Chen commented
> Is System V IPC required?

For my understanding, System V IPC is required for ALSA.
If System V IPC is disabled, you will get a message of `pcm_direct.c:2188:(snd pcm_direct new) unable to create IPC semaphore`  when running `speaker-test` (the `speaker-test` is part of `alsa-utils` for speaker testing).

2024-09-14 03:23 UTC, jserv requested changes
Rebase the latest `master` branch and resolve conflicts.

2024-09-15 14:42 UTC, jserv commented on virtio-snd.c
> +        /* TO-DO: should read the config */
Use `TODO` notation.

2024-09-15 14:42 UTC, jserv commented on virtio-snd.c
> +        /* TO-DO: detect current state of stream */
Ditt.

2024-09-17 03:58 UTC, jserv commented on virtio-snd.c
> +enum {
Add comments here.

2024-09-17 04:00 UTC, jserv commented on virtio-snd.c
> +    /* virtio-snd uses three virtqueue descriptors
Improve the English writing.

2024-09-17 04:25 UTC, jserv commented on virtio-snd.c
> +    for (int i = 0; i < 3; i++) {
Can you avoid hardcoded `3`?

2024-09-17 13:54 UTC, jserv commented on Makefile
> +$(if $(shell echo '\#include <alsa/asoundlib.h>\nint main\(\){return 0;}' | $(CC) -x c -lasound -o /dev/null > /dev/null 2> /dev/null - && echo $$?),0,1)
Make the generation of C test program modular. See https://github.com/sysprog21/shecc/blob/master/mk/riscv.mk and https://github.com/sysprog21/shecc/blob/master/Makefile#L44-L47

2024-09-20 11:33 UTC, jserv commented on Makefile
> +	$(call create-alsa-prog) > $@
You don't have to leave the file `check-alsa.c`.
Try`$(shell $(call create-alsa-prog) | $(CC) -x c -)`

2024-09-21 15:56 UTC, jserv commented on mk/check_lib.mk
> +	return 0;\n$\
You should check ALSA functions as well. At least, the initializer.

2024-09-21 16:01 UTC, jserv commented on virtio-snd.c
> +    VIRTIO_SND_PCM_RATE_5512 = 0,
The comments should contain something like `/* 5512Hz */`.

2024-09-22 04:51 UTC, jserv commented on Makefile
> +include mk/check_lib.mk
Rename to `mk/check-libs.mk` .

2024-09-22 09:46 UTC, jserv commented
Fix unintended error when running `make clean`.
```
/bin/sh: 1: @env: not found
```

2024-09-22 09:49 UTC, jserv commented on Makefile
> +ifeq (0, $(shell $(call create-alsa-prog) | $(CC) -x c -lasound -o /dev/null > /dev/null 2> /dev/null - && echo $$?))
You should wrap the operations in `mk/check-libs.mk`.

2024-09-22 10:09 UTC, jserv commented on mk/check-libs.mk
> +# Create a mininal ALSA program
Consider the shorter form:
```shell
define create-alsa-prog
echo '\                                                                                                                                           
#include <alsa/asoundlib.h>\n\
int main(){\n\
    snd_pcm_t *pcm;\n\
    snd_pcm_open(&pcm, "default", SND_PCM_STREAM_PLAYBACK, 0);\n\
    snd_pcm_close(pcm);\n\
    return 0;\n\
}\n'
endef
```

2024-09-22 10:12 UTC, jserv commented on mk/check-libs.mk
> +# Create a mininal ALSA program
Alternatively, try this:
```shell
define create-alsa-prog
$(PRINTF) '%s\n' '#include <alsa/asoundlib.h>' \
'int main() {' \
'    snd_pcm_t *pcm;' \
'    snd_pcm_open(&pcm, "default", SND_PCM_STREAM_PLAYBACK, 0);' \                                                                                            
'    snd_pcm_close(pcm);' \
'    return 0;' \
'}'
endef
```

Don't use `$(Q)` inside the definitions.

2024-09-22 12:36 UTC, Cuda-Chen commented on mk/check-libs.mk
> +# Create a mininal ALSA program
@jserv, 
Thanks for the suggestions!
It also solve the issue of `/bin/sh: 1: @env: not found`.

2024-09-22 13:49 UTC, jserv commented on mk/check-libs.mk
> +	echo '\
Don't indent the `echo`.

2024-09-22 13:50 UTC, jserv commented on mk/check-libs.mk
> +	#include <alsa/asoundlib.h>\n\
Remove the leading space characters for simplicity.

2024-09-26 03:17 UTC, jserv commented on virtio-snd.c
> +    return addr >> 2;
?

2024-09-26 03:18 UTC, jserv commented on virtio-snd.c
> +    /* Check le32 len field of `struct virtq_used_elem` on the spec  */
Don't use [backticks](https://en.wikipedia.org/wiki/Backtick).

2024-09-30 05:48 UTC, jserv requested changes
Provide the test procedures, so that reviewers can be involved.

2024-10-02 03:16 UTC, Cuda-Chen commented
> Provide the test procedures, so that reviewers can be involved.

Hi @jserv ,

Though there are a litter information for testing VirtIO device, I list the possible test cases in the first comment.

2024-10-02 03:59 UTC, jserv commented
> Execute speaker-test in emulator.
> Check the host speaker.
> expected results
> A white noise will be played by host speaker while speaker-test is executing.

What features or functionalities are missing that prevent aplay from playing wave files?

2024-10-02 08:14 UTC, Cuda-Chen commented
> > Execute speaker-test in emulator.
> > Check the host speaker.
> > expected results
> > A white noise will be played by host speaker while speaker-test is executing.
> 
> What features or functionalities are missing that prevent aplay from playing wave files?

Hi @jserv ,

For my understanding and observation, we lack two things:

1. sound card: as `aplay` can select sound card yet I don't get any information about `VirtIO SoundCard at platform/f4400000.virtio/virtio2`.
2. PCM: `aplay` triggers PCM related function to play sound. However, for virtio-snd, I am still working on the PCM part (`VIRTIO_SND_R_PCM_*`) especially filling the buffer to ALSA.

2024-10-07 09:00 UTC, jserv commented on virtio-snd.c
> +    virtio_snd_jack_info_t *info =
It is not necessary to cast the result (`void *`) in C programs.

2024-11-16 15:21 UTC, jserv commented on virtio-snd.c
> +    sleep(1);
Why `sleep(1)` here?

2024-12-15 13:29 UTC, jserv commented on device.h
> +    uint32_t *ram;
I am not sure `ram` is proper here. Should it be `mem`?

2024-12-15 13:32 UTC, jserv requested changes
Move the content of `queue.h` to `utils.h` as [rv32emu does](https://github.com/sysprog21/rv32emu/blob/master/src/utils.h). Then, enforce the Linux-like naming scheme.

2024-12-15 13:34 UTC, jserv commented on virtio-snd.c
> +};
Use [X macro](https://en.wikipedia.org/wiki/X_macro) technique to shorten the code.

2024-12-15 13:35 UTC, jserv commented on virtio-snd.c
> +#define VSND_RING_SZ_MASK (uint32_t)(0x0fffffff) /* ring size mask */
Rewrite as `0x0FFFFFFFULL` without casting.

2024-12-15 13:36 UTC, jserv commented on virtio-snd.c
> +    PRIV(vsnd)->controls = controls;
Can you use `memcpy` instead?

2024-12-15 13:38 UTC, jserv commented on virtio-snd.c
> +    /* TODO: add lock to avoid race condition */
You may consolidate the testing for producer-consumer implementation in advance.

2024-12-16 03:29 UTC, jserv commented
Consider the way to use [X macro](https://en.wikipedia.org/wiki/X_macro):
```diff
--- a/virtio-snd.c
+++ b/virtio-snd.c
@@ -64,31 +64,34 @@ enum {
     VIRTIO_SND_S_IO_ERR,
 };
 
+/* Unit: Hz */
+#define SND_PCM_RATE \
+    _(5512)          \
+    _(8000)          \
+    _(11025)         \
+    _(16000)         \
+    _(22050)         \
+    _(32000)         \
+    _(44100)         \
+    _(48000)         \
+    _(64000)         \
+    _(88200)         \
+    _(96000)         \
+    _(176400)        \
+    _(192000)        \
+    _(384000)
+
 /* supported PCM frame rates */
 enum {
-#define _(rate) VIRTIO_SND_PCM_RATE_##rate
-    _(5512) = 0, /* 5512 Hz */
-    _(8000),     /* 8000 Hz */
-    _(11025),    /* 11025 Hz */
-    _(16000),    /* 16000 Hz */
-    _(22050),    /* 22050 Hz */
-    _(32000),    /* 32000 Hz */
-    _(44100),    /* 44100 Hz */
-    _(48000),    /* 48000 Hz */
-    _(64000),    /* 64000 Hz */
-    _(88200),    /* 88200 Hz */
-    _(96000),    /* 96000 Hz */
-    _(176400),   /* 176400 Hz */
-    _(192000),   /* 192000 Hz */
-    _(384000),   /* 384000 Hz */
+#define _(rate) VIRTIO_SND_PCM_RATE_##rate,
+    SND_PCM_RATE
 #undef _
 };
 
 /* supported PCM frames rates mapping */
 int pcm_rate_tbl[] = {
-#define _(rate) [VIRTIO_SND_PCM_RATE_##rate] = rate
-    _(5512),  _(8000),  _(11025), _(16000), _(22050),  _(32000),  _(44100),
-    _(48000), _(64000), _(88200), _(96000), _(176400), _(192000), _(384000),
+#define _(rate) [VIRTIO_SND_PCM_RATE_##rate] = rate,
+    SND_PCM_RATE
 #undef _
 };

```

It is now shorter and easier to maintain.

2024-12-17 09:05 UTC, Cuda-Chen commented on virtio-snd.c
> +    PRIV(vsnd)->controls = controls;
Hi @jserv , it seems that copying certain members of a struct using `dst->foo = src->foo` will be the sane way according [this StackOverflow answer](https://stackoverflow.com/a/61117514).

2024-12-17 10:06 UTC, Cuda-Chen commented on device.h
> +    uint32_t *ram;
I just copy-and-paste from `virtio-net.c`. Maybe we can make a difference in this commit?

2024-12-17 16:45 UTC, jserv commented on queue.h
> +#ifndef QUEUE_H
Drop `queue.h` in favor of `utils.h`.

2024-12-17 16:46 UTC, jserv commented on utils.h
> +/* Linux-like queue API */
Let's enforce the Linux kernel style naming scheme.

2024-12-18 04:45 UTC, jserv commented
> * For playing the sound (PCM):
>   * [x]  `VIRTIO_SND_R_PCM_START`
>   * [ ]  `VIRTIO_SND_R_PCM_STOP`

I can build on macOS with CoreAudio support now. What is missing to complete PCM functionality?

2024-12-18 04:49 UTC, Cuda-Chen commented on virtio-snd.c
> +    asm("" ::: "memory");
I create a compiler barrier to make sure the data has to been written to ring buffer thus prevent race condition (see [the DPDK counterpart](https://github.com/scylladb/dpdk/blob/master/lib/librte_ring/rte_ring.h#L555)).

2024-12-18 04:58 UTC, Cuda-Chen commented
> > * For playing the sound (PCM):
> >   
> >   * [x]   `VIRTIO_SND_R_PCM_START`
> >   * [ ]   `VIRTIO_SND_R_PCM_STOP`
> 
> I can build on macOS with CoreAudio support now. What is missing to complete PCM functionality?

Hi @jserv , I list the messing parts for completing PCM functionality:

1. Clean the allocated resources after issuing `VIRTIO_SND_R_PCM_RELEASE`: on my Linux testing machine, because of PulseAudio, the guest OS hangs when closing the created ALSA device. However, we can't create ALSA device after disabling PulseAudio.
    - Edit: The checked list of `VIRTIO_SND_R_PCM_RELEASE` is wrong, I am still finding solutions of co-working with PulseAudio.
2. No sound after `VIRTIO_SND_R_PCM_START`: I do not hear any sound after issuing `VIRTIO_SND_R_PCM_START` state on my Linux testing machine.

For testing, I come up with the following two methods and the corresponding expected results:

1. `speaker-test`
  - expected result: a white noise should be played.
2. `aplay <any audio file>`
  - expected results: the audio should be played without any artifacts (e.g., distortion, lagging, etc.).

2024-12-18 04:59 UTC, shengwen-tw commented on virtio-snd.c
> +    asm("" ::: "memory");
If this is necessary, I will suggest wrapping it with macro for readability.

2024-12-27 17:33 UTC, jserv commented
Is it time to review?

2024-12-28 00:07 UTC, Cuda-Chen commented
> Is it time to review?

Hi @jserv ,
Not yet, as I am still working on the following three issues:

1. Output sound only contains the beginning.
2. `semu` hangs at pcm_release state.
3. Some code hygienes.

2025-01-19 04:17 UTC, Cuda-Chen commented
Hi @jserv ,
After playing the sound whole month, I consider that there might be a pitfall of my implementation of playing sound or the Linux Kernel version this project is using.

The virtio-snd plays the sound with repeating artifact (taking "front center" as example, it sounds like "front front center").

Kindly leave some thoughts for some references or some folks of dealing with repeating artifact if I had a chance, and it will be a great thanks for your help!

If you would like to get the file, I will convert the file into base64 encoded text in order to upload to here.

2025-01-22 05:11 UTC, jserv commented
> If you would like to get the file, I will convert the file into base64 encoded text in order to upload to here.

Simply share the prebuilt Linux kernel image file, rootfs, and test files via Google Drive, Dropbox, or similar services as they are intended to be temporary.

2025-01-22 07:36 UTC, Cuda-Chen commented
Hi @jserv ,

This Dropbox share link contains the files that reviewers will need: https://www.dropbox.com/scl/fo/vv3luiccfco5tjwt8tqxm/AANAyYgL9qvVPhuT4dtkkIA?rlkey=dv84qtw9y4e0ea8go03q5qwf8&st=73j9agts&dl=0

The usage of files are described as follows:
1. `Image`: guest Linux OS image.
2. `rootfs.cpio`: disk image.
3. `out_stream.bin`: a binary dump of output stream (i.e., the `Front_Center.wav` of ALSA sound example). You can use `aplay` to play the file like this: `cat out_stream.bin | aplay --format=S16_LE --rate=48000 -`.

2025-01-23 09:10 UTC, jserv commented
Tested on macOS + Apple M1:
```
# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: SoundCard [VirtIO SoundCard], device 0: virtio-snd [VirtIO PCM 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
# aplay /usr/share/sounds/alsa/Front_Center.wav
Playing WAVE '/usr/share/sounds/alsa/Front_Center.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Mono
CoreAudio: from: [O/I] (null)/(null) (semu-virtio-snd) / (48000,0)x(1,0) (4800)
```

Then, it got stuck without progress.

2025-01-23 09:17 UTC, Cuda-Chen commented
> Then, it got stuck without progress.

Thanks for helping the tests on macOS. I guess it is some kind of locking issue.
While trying to fix, I would like to ask whether a "front center" sound comes out from host or not while executing `aplay /usr/share/sounds/alsa/Front_Center.wav`?

2025-01-23 09:54 UTC, jserv commented
Consider the change below to suppress compilation warnings raised by CNFA:
```diff
--- a/Makefile
+++ b/Makefile
@@ -85,6 +85,7 @@ CNFA_LIB := cnfa/CNFA_sf.h
 $(CNFA_LIB): cnfa/Makefile cnfa/os_generic
        $(MAKE) -C $(dir $<) CNFA_sf.h
 main.o: $(CNFA_LIB)
+virtio-snd.o: CFLAGS += -Wno-unused-parameter
 endif
 
 # .DEFAULT_GOAL should be set to all since the very first target is not all
```

2025-01-23 10:29 UTC, Cuda-Chen commented
Hi @jserv ,

> Then, it got stuck without progress.

After checking the CNFA part, the coreaudio just like the PulseAudio/PipeWire part: no need to use a dedicated thread for pushing PCM frames.

I would like to ask which one you prefer for resolving this issue:
1. Exclude macOS support.
    - No need to change the threading model of pushing PCM.
2. Use PulseAudio/PipeWire solution.
    - Threading module of pushing PCM frames need to be re-designed.

2025-01-23 13:32 UTC, jserv commented on virtio-snd.c
> +int pcm_rate_tbl[] = {
Declare it as a `static` array.

2025-01-23 14:10 UTC, Cuda-Chen commented on virtio-snd.c
> +int pcm_rate_tbl[] = {
Done.

2025-02-01 12:51 UTC, jserv commented on utils.h
> +#ifdef __list_HAVE_TYPEOF
The `typeof` is necessary to build. Check it and alert if no gcc/clang is found.

2025-02-01 15:50 UTC, jserv commented on utils.h
> +#define __LIST_HAVE_TYPEOF 1
Rename `__LIST_HAVE_TYPEOF` to `__HAVE_TYPEOF`.

2025-02-01 15:50 UTC, jserv commented on utils.h
> +#define container_of(ptr, type, member)                            \
You don't have to check `__LIST_HAVE_TYPEOF` here.

2025-02-01 15:51 UTC, jserv commented on utils.h
> +#ifdef __LIST_HAVE_TYPEOF
Ditto. Don't check `__LIST_HAVE_TYPEOF`.

2025-02-02 02:44 UTC, merged

2025-02-02 02:44 UTC, jserv commented
Thank @Cuda-Chen for contributing!