CI: build on macOS
sysprog21/semu pull request #59
Opened 2024-09-09 16:17 UTC by ChinYikMing

2024-09-09 16:21 UTC, ChinYikMing commented
When running boot tests on macOS, the kernel gets stuck at the following message:

`[ 3062.927108] sched_clock: 64 bits at 65MHz, resolution 15ns, wraps every 2199023255550ns`

After bisecting, #49 was identified as the cause of the issue. Cc: @chiangkd

2024-09-10 19:10 UTC, chiangkd commented
Hi @ChinYikMing ,

I noticed an abnormal timestamp in the boot log:
> `[ 3062.927108] sched_clock: 64 bits at 65MHz, resolution 15ns, wraps every 2199023255550ns`

This issue arises because I inadvertently returned the clocksource in nanoseconds when building on macOS, while the expected unit is seconds.

```diff
static uint64_t semu_timer_clocksource(uint64_t freq)
{
#if defined(HAVE_POSIX_TIMER)
    struct timespec t;
    clock_gettime(CLOCKID, &t);
    return t.tv_sec * freq + mult_frac(t.tv_nsec, freq, 1e9);
#elif defined(HAVE_MACH_TIMER)
    static mach_timebase_info_data_t t;
    if (t.denom == 0)
        (void) mach_timebase_info(&t);
-    return mult_frac(mach_absolute_time() * freq, t.numer, t.denom);
+    return mult_frac(mult_frac(mach_absolute_time(), freq, 1e9), t.numer, t.denom);
#else
    return time(0) * freq;
#endif
}
```

I will create another PR to fix this bug. Thanks for pointing it out!

Regarding the CI test failures, the CI workflow was failing due to a timeout (currently set to 90 seconds), I found some [discussion](https://github.com/actions/runner-images/issues/1336) about github-hosted runner. When I increasing timeout value to 600 seconds [allowed the workflow to pass](https://github.com/chiangkd/semu/actions/runs/10798598092), I am not sure where is the bottleneck during workflow but it actually take much more time to boot linux on semu with macOS runner. I'm also exploring options to build semu on a real macOS machine to better address this issue.

2024-09-12 07:56 UTC, jserv requested changes
Rebase the latest `master` branch.

2024-09-12 16:46 UTC, ChinYikMing commented
@chiangkd ，Is the 600s timeout the minimum needed to pass the CI on the macOS runner? I would prefer adding a condition based on the runner to select the appropriate timeout duration. After that, a new issue can be created to track this.

2024-09-12 18:08 UTC, ChinYikMing commented
> Rebase the latest `master` branch.

Done.

2024-09-12 19:10 UTC, chiangkd commented
> @chiangkd , Is the 600s timeout the minimum needed to pass the CI on the macOS runner? I would prefer adding a conditional statement based on the runner to select the appropriate timeout duration. After that, a new issue can be created to track this.

In my testing, the average time to pass this Action is around 311 seconds. Additionally, I reverted to using the `mtime` counter instead of the real-time clock, which brought the execution time down to about 135 seconds, 

- [Test with realtime clocksource](https://github.com/chiangkd/semu/actions/runs/10798598092)
- [Test with mtime counter](https://github.com/chiangkd/semu/actions/runs/10836556878).

I also tested running semu on macOS via VirtualBox, but it still took longer to boot the system.

Here are the results for `make check` on macOS through VirtualBox:
```shell
...
[142.702404] Run/ init as init process
...
```

2024-09-13 02:34 UTC, jserv commented on .ci/autorun.sh
> +UNAME_S=$(uname -s)
Add proper comments to address the difference.

2024-09-13 19:28 UTC, ChinYikMing commented
> > @chiangkd , Is the 600s timeout the minimum needed to pass the CI on the macOS runner? I would prefer adding a conditional statement based on the runner to select the appropriate timeout duration. After that, a new issue can be created to track this.
> 
> In my testing, the average time to pass this Action is around 311 seconds. Additionally, I reverted to using the `mtime` counter instead of the real-time clock, which brought the execution time down to about 135 seconds,
> 
> * [Test with realtime clocksource](https://github.com/chiangkd/semu/actions/runs/10798598092)
> * [Test with mtime counter](https://github.com/chiangkd/semu/actions/runs/10836556878)
> 
> I also tested running semu on macOS via VirtualBox, but it still took longer to boot the system.
> 
> Here are the results for `make check` on macOS through VirtualBox:
> 
> ```shell
> ...
> [142.702404] Run/ init as init process
> ...
> ```

Got it, thanks for testing. It looks like 600 seconds is sufficient to pass the CI on the macOS runner.

2024-09-14 03:22 UTC, merged

2024-09-14 03:22 UTC, jserv commented
Thank @ChinYikMing for contributing!