Fix incorrect clock calculation on macOS
sysprog21/semu pull request #60
Opened 2024-09-10 19:21 UTC by chiangkd

The current `semu_timer_clocksource()` returns the clock source in nanoseconds when building on macOS. Causing an abnormal timestamp in the boot log.
```
...
[ 3062.927108] sched_clock: 64 bits at 65MHz, resolution 15ns, wraps every 2199023255550ns
```
Divide the return value by 1e9, ensuring the clock source is provided in seconds.

2024-09-10 19:37 UTC, ChinYikMing commented
Change `MacOS` in the commit title to `macOS`.

2024-09-10 19:37 UTC, ChinYikMing commented
Issue found in #59.

2024-09-10 20:01 UTC, ChinYikMing commented
> Change `MacOS` in the commit title to `macOS`.

Also the title in the commit, you may force push after changing.

2024-09-11 00:36 UTC, jserv requested changes
Improve the git commit message.

2024-09-12 07:55 UTC, merged

2024-09-12 07:55 UTC, jserv commented
Thank @chiangkd for contributing!