Preliminary ACLINT implementation
sysprog21/semu pull request #66
Opened 2024-12-12 08:22 UTC by Mes0903

In this commit, based on the implementation of CLINT, an preliminary ACLINT is implemented, including the basic logic for operating `mtimer`, `mswi`, and `sswi`.

Additionally, introduces a new script `gen-hart-dts.py` for generating device-tree configurations and renames the original script to `gen-clint-dts.py`. The new script is currently unused.

A new macro `SEMU_FEATURE_ACLINT` is also added to feature.h, allowing the replacement of CLINT with ACLINT in the implementation.

Currently, due to the lack of implementation, the introduced ACLINT uses only supervisor-level IPI. Therefore, although the logic for mswi is implemented, it is not being used at the moment.

It can be tested by `make check SMP=n`, where n is the number of harts you want to simulate.

2024-12-12 17:26 UTC, chiangkd commented on aclint.c
> +}
Let's do [add a new line to the end of a file](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2024-12-12 17:44 UTC, chiangkd commented on Makefile
> +	aclint.o \
I'm uncertain if the CLINT-related implementation will still exist once ACLINT is fully implemented. If it does, add an option here to use CLINT when ACLINT is unavailable.

2024-12-13 21:21 UTC, Mes0903 commented on feature.h
> +#endif
Added a flag `ENABLE_ACLINT` in the Makefile, allowing users to choose whether to enable ACLINT. By default, ACLINT is disabled (inspired by QEMU). If enabled, ACLINT will be used instead of CLINT.

2024-12-13 21:24 UTC, Mes0903 commented
In the latest commit, `ENABLE_ACLINT` was added to the Makefile. This flag determines whether to use CLINT or ACLINT, with CLINT being the default.

2024-12-14 02:29 UTC, jserv commented
> In the latest commit, `ENABLE_ACLINT` was added to the Makefile. This flag determines whether to use CLINT or ACLINT, with CLINT being the default. The ACLINT can be tested by `make check SMP=n ENABLE_ACLINT=1` now.

I don't think we should maintain both CLINT and ACLINT implementation.  The RISC-V Advanced Core Local Interruptor (ACLINT) enhances the existing SiFive CLINT design through several key improvements:
* Modular Architecture: ACLINT adopts a modular approach by separating timer and inter-processor interrupt (IPI) functionalities into distinct devices. This design enables RISC-V platforms to selectively implement only the necessary components, providing greater flexibility in system design.
* Dedicated S-Level IPI Device: The specification introduces a dedicated memory-mapped I/O (MMIO) device specifically for supervisor-level IPIs. This innovation eliminates the need to use Supervisor Binary Interface (SBI) calls for interrupt communication in Linux RISC-V systems, streamlining interrupt handling.
* Multi-Instance Support: ACLINT supports multiple timer and IPI device instances, a critical feature for multi-socket or multi-die Non-Uniform Memory Access (NUMA) system architectures. This capability allows for more complex and scalable system designs.
* Backward Compatibility: The specification maintains full compatibility with the original SiFive CLINT, ensuring that existing RISC-V platforms can seamlessly conform to the new ACLINT specification without requiring extensive redesigns or hardware modifications.

The recent Linux kernel now provides support for ACLINT, and QEMU has also integrated this feature, allowing users to enable it through the `-machine virt,aclint=on` option. Given these developments, it is an opportune time to transition to the ACLINT architecture.

2024-12-14 05:38 UTC, Mes0903 commented
The final commit removed all implementations of CLINT, including the previously introduced `ENABLE_ACLINT` and `OBJS_IR_CTRL`. Currently, the project only contains the implementation of ACLINT.

2024-12-14 07:06 UTC, jserv commented
Check https://cbea.ms/git-commit/ carefully and enforce the rules.

2024-12-14 08:58 UTC, Mes0903 commented
Due to two minor issues in the first commit of this PR—specifically, the absence of `#address-cells = <0>` causing DTC warnings, and the lack of a newline at the end of `aclint.c`—two additional small commits were added, making the commit history cluttered, also the commit message didn't follow the rule listed in https://cbea.ms/git-commit/.

To address this, the first commit message has been rewritten in accordance with the commit message rules, and the two minor issues have also been fixed in the process.

2024-12-14 14:43 UTC, jserv requested changes
Don't use [backticks](https://en.wikipedia.org/wiki/Backtick) for the sake of terminal compatibility. Use single quotation marks instead.

2024-12-14 14:50 UTC, jserv requested changes
Improve git commit messages by:
1. Clearly articulating the rationale behind transitioning from CLINT to ACLINT, highlighting the motivations and potential benefits of this migration.
2. Detailing the methodological approach for verifying and validating the functionalities of the proposed ACLINT support, including specific testing strategies or validation criteria.
3. Summarize the Linux kernel support on ACLINT along with git revisions.
4. Outlining potential future development paths to enhance and complete the SMP  support, identifying specific areas for improvement or expansion.

By the way, it is not necessary to mention "preliminary" if the proposed change covers the functionalities of CLINT. Instead, the major consideration is to migrate.

2024-12-14 14:52 UTC, jserv commented on aclint.c
> +     * @brief `addr & 0x4` is used to determine the upper or lower 32 bits
Don't use `@brief` notation. Instead, express in plain and informative English sentences.

2024-12-14 14:52 UTC, jserv commented on aclint.c
> +     * @brief The `cmp_val & 0xFFFFFFFF` is used to select the upper 32 bits
Ditto.

2024-12-14 14:53 UTC, jserv commented on aclint.c
> +     * @brief `addr & 0x4` is used to determine the upper or lower 32 bits
Don't use backtick. Use single quotation marks instead.

2024-12-14 14:53 UTC, jserv commented on device.h
> +    uint32_t msip[4096];  // Machine Software Interrupt Pending array
Always use C-style comments.

2024-12-14 14:54 UTC, jserv commented on device.h
> +    uint32_t ssip[4096];  // Supervisor Software Interrupt Pending array
Ditto. Explain why 4096 appears here.

2024-12-15 09:50 UTC, Mes0903 commented
The latest commit includes the following updates:

- Unified the use of C-style comments throughout the code.
- Removed the `@brief` notation, replacing it with plain and informative sentences.
- Replaced backticks with single quotation marks for consistency.
- Elaborated on the fundamental principles behind the transition from CLINT to ACLINT, emphasizing the motivations and benefits of this migration.
- Summarized Linux kernel support for ACLINT along with relevant git revisions.
- Provided detailed instructions on how to validate ACLINT functionalities, including specific testing strategies and validation methods.
- Outlined potential future development paths to enhance and complete SMP support, specifying areas for improvement or expansion.

2024-12-15 09:55 UTC, jserv commented
> The latest commit includes the following updates:

Don't attempt to summarize your changes. Instead, we always care about the changesets. Let's consolidate each git commit without unnecessary report.

2024-12-15 09:57 UTC, jserv commented on aclint.c
> +    *value >>= (RV_MEM_SW - width);
Rewrite as `*value >>= RV_MEM_SW - width` for short. The parentheses should only appear for the sake of the necessity.

2024-12-15 09:58 UTC, jserv commented on aclint.c
> +    *value >>= (RV_MEM_SW - width);
Ditto. Eliminate the parentheses.

2024-12-15 10:00 UTC, jserv commented on device.h
>      uint64_t mtimecmp[4095];
The pre-allocated `mtimecmp` causes unexpected memory waste since we don't really need all of its members. Consider allocating it on-demand.

2024-12-15 10:01 UTC, jserv commented on device.h
> +    uint32_t msip[4096];
Since the 4096th MSIP register is reserved, does it make sense to allocate 4096 elements?

2024-12-15 10:04 UTC, Mes0903 commented on device.h
> +    uint32_t msip[4096];
ok, maybe I can allocate it based on the value of `SMP` specified during compilation.

2024-12-15 10:09 UTC, jserv requested changes
Place proper `FIXME` and `TODO` comments to indicate the next step.

2024-12-15 12:35 UTC, jserv commented on Makefile
> +CFLAGS += -DNUM_HARTS=$(SMP)
Don't do that. The use of ACLINT is transparent, meaning that it can be applied to uniprocessor configurations as well.

2024-12-15 12:36 UTC, jserv commented on device.h
> +#endif
Ditto. Remove the uncertain code.

2024-12-15 12:37 UTC, jserv commented on device.h
> +    uint64_t mtimecmp[NUM_HARTS];
Allocate via runtime instead of build-time.

2024-12-15 12:38 UTC, jserv commented on main.c
> +    /* TODO: Complete RFENCE SBI extension to support parallel multi-core
It was not meant to be "parallel." Check the spec.

2024-12-15 12:38 UTC, jserv commented on main.c
> +        /* TODO: Implement parallel multi-core simulation */
Refine the wording.

2024-12-15 13:15 UTC, Mes0903 commented on main.c
> +    /* TODO: Complete RFENCE SBI extension to support parallel multi-core
Sorry for the imprecise wording. What I intended to express is that the current simulation executes sequentially. After reviewing the spec, I think the more precise term should be "concurrent multithreaded emulation".

2024-12-15 13:19 UTC, jserv commented on main.c
> +    /* TODO: Complete RFENCE SBI extension to support parallel multi-core
> Sorry for the imprecise wording. What I intended to express is that the current simulation executes sequentially. After reviewing the spec, I think the more precise term should be "concurrent multi-threaded emulation".

Use "multi-threaded system emulation" instead. See https://www.qemu.org/docs/master/devel/multi-thread-tcg.html
[Concurrency is not Parallelism](https://youtu.be/oV9rvDllKEg) by Rob Pike.

2024-12-15 13:21 UTC, jserv commented on main.c
> +    /* TODO: Complete RFENCE SBI extension to support parallel multi-core
> Sorry for the imprecise wording.

You don't have to say "sorry" early. The most polite way to express is to get things done right after you make a mistake.

2024-12-15 14:37 UTC, Mes0903 commented
Refine the wording in both comments and the previous git commit message. And use `calloc` to allocate the registers in ACLINT at runtime.

2024-12-16 01:26 UTC, merged

2024-12-16 01:26 UTC, jserv commented
Thank @Mes0903 for contributing!